from typing import AsyncIterator, Protocol, runtime_checkable

from app.market.schemas import Candle, Snapshot


@runtime_checkable
class MarketSource(Protocol):
    async def get_snapshot(self, ticker: str) -> Snapshot: ...
    async def get_daily_candles(self, ticker: str, count: int = 60) -> list[Candle]: ...
    async def get_candles(self, ticker: str, period: str = "D", count: int = 60) -> list[Candle]: ...
    async def stream_snapshots(self, tickers: list[str]) -> AsyncIterator[dict[str, Snapshot]]: ...
